
#ifndef AST_OBJECT_TYPE_H_
#define AST_OBJECT_TYPE_H_

namespace ast {

  enum ObjectType {SIGNAL, VARIABLE, CONSTANT, FUNCTION, PROCEDURE, PORT, TYPE, ENUM, ENTITY, CONFIGURATION, SUBTYPE, FILE, GROUP, ARCHITECTURE, PACKAGE, COMPONENT};

}

#endif
