#include <cassert>
#include <algorithm>
#include <string>

#include "parameters.hpp"

namespace generator {

  void parameters::FileContainer::flush(bool verbose) {
    std::ofstream header_file;
    std::ofstream implementation_file;
    std::string header_file_name = replaceFileExtension(file_name, ".hpp");
    header_file.open(header_file_name);
    implementation_file.open(replaceFileExtension(file_name, ".cpp"));
    content.implementation_top.push_front("#include \"" + header_file_name + "\"");
    std::string header_def = file_name + "_HPP";
    std::replace(header_def.begin(), header_def.end(), '.', '_');
    std::transform(header_def.begin(), header_def.end(), header_def.begin(), ::toupper);
    header_file << "#ifndef " << header_def << std::endl;
    header_file << "#define " << header_def << std::endl;
    content.include.push_front("#include <string.h>");
    content.include.push_front("#include <systemc.h>");
    content.include.push_front("#include <vhdl.h>");
    content.namespace_start = "namespace vhdl { namespace " + library + " {";
    content.namespace_end = "}} // namespace end ";
    if (verbose) {
      header_file << "// Autogenerated from source " << file_name << std::endl;
      implementation_file << "// Autogenerated from source " << file_name << std::endl;
    }
    content.flush(header_file, implementation_file, 0, verbose);
    header_file << "#endif" << std::endl;
    header_file.close();
    implementation_file.close();
  }

  parameters::ClassContainer* parameters::FileContainer::getCurrentClassContainer() {
    debug.functionStart("getCurrentClassContainer");
    ClassContainer* a = NULL;
    if (!content.children.empty()) {
      ClassContainer& x = content.children.back();
      if (x.active) {
	a = &x;
	int index = 0;
	bool done = false;
	do {
	  debug.debug("Index = " + std::to_string(index));
	  if (a->children.empty()) {
	    done = true;
	  } else {
	    ClassContainer& x = a->children.back();
	    if (x.active) {
	      a = &x;
	    } else {
	      done = true;
	    }
	  }
	  index++;
	} while (!done);
      }
    }
    debug.functionEnd("getCurrentClassContainer");
    return a;
  }
  
}
